# Numpy_Part_2

In [ ]:
#Numpy - Array Manipulation.

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10 , (3,4))

In [ ]:
arr

array([[8, 8, 6, 8],
       [4, 2, 8, 2],
       [3, 4, 5, 7]])

In [ ]:
arr.reshape(6,2)

array([[8, 8],
       [6, 8],
       [4, 2],
       [8, 2],
       [3, 4],
       [5, 7]])

In [ ]:
arr.reshape(2,6)

array([[8, 8, 6, 8, 4, 2],
       [8, 2, 3, 4, 5, 7]])

In [ ]:
arr.reshape(2,-242342)

array([[8, 8, 6, 8, 4, 2],
       [8, 2, 3, 4, 5, 7]])

In [ ]:
arr.T

array([[8, 4, 3],
       [8, 2, 4],
       [6, 8, 5],
       [8, 2, 7]])

In [ ]:
arr

array([[8, 8, 6, 8],
       [4, 2, 8, 2],
       [3, 4, 5, 7]])

In [ ]:
arr.flatten()

array([8, 8, 6, 8, 4, 2, 8, 2, 3, 4, 5, 7])

In [ ]:
arr1 = np.array([1,2,3,3,4])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
arr1.ndim

1

In [ ]:
np.expand_dims(arr1 ,axis=1) # expanded dimension from 1 to 2 column

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [ ]:
np.expand_dims(arr1 ,axis=0)  # expanded dimension from 1 to 2 row

array([[1, 2, 3, 3, 4]])

In [ ]:
arr

array([[8, 8, 6, 8],
       [4, 2, 8, 2],
       [3, 4, 5, 7]])

In [ ]:
np.squeeze(arr) # not for this

array([[8, 8, 6, 8],
       [4, 2, 8, 2],
       [3, 4, 5, 7]])

In [ ]:
data = np.array([[1] , [2] , [3]])

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.squeeze(data) # for single element

array([1, 2, 3])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [ ]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

In [ ]:
np.roll(arr1 , 2)

array([3, 4, 1, 2, 3])

In [ ]:
np.roll(arr1 , 5)

array([1, 2, 3, 3, 4])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
#Numpy - Binary Operators.

In [ ]:
arr1 = np.random.randint(1,10 , (3,4))

In [ ]:
arr2 = np.random.randint(1,10 , (3,4))

In [ ]:
arr1

array([[7, 2, 6, 4],
       [1, 3, 6, 7],
       [3, 3, 1, 9]])

In [ ]:
arr2

array([[2, 7, 9, 5],
       [3, 1, 1, 5],
       [8, 9, 5, 1]])

In [ ]:
arr1+arr2

array([[ 9,  9, 15,  9],
       [ 4,  4,  7, 12],
       [11, 12,  6, 10]])

In [ ]:
arr1*arr2 # index operation

array([[14, 14, 54, 20],
       [ 3,  3,  6, 35],
       [24, 27,  5,  9]])

In [ ]:
arr1/arr2

array([[3.5       , 0.28571429, 0.66666667, 0.8       ],
       [0.33333333, 3.        , 6.        , 1.4       ],
       [0.375     , 0.33333333, 0.2       , 9.        ]])

In [ ]:
arr1-arr2

array([[ 5, -5, -3, -1],
       [-2,  2,  5,  2],
       [-5, -6, -4,  8]])

In [ ]:
arr1%arr2 # reminder operation

array([[1, 2, 6, 4],
       [1, 0, 0, 2],
       [3, 3, 1, 0]])

In [ ]:
arr1 ** arr2 # power operation

array([[      49,      128, 10077696,     1024],
       [       1,        3,        6,    16807],
       [    6561,    19683,        1,        9]])

In [ ]:
arr1 & arr2 # and operation

array([[2, 2, 0, 4],
       [1, 1, 0, 5],
       [0, 1, 1, 1]])

In [ ]:
arr1

array([[7, 2, 6, 4],
       [1, 3, 6, 7],
       [3, 3, 1, 9]])

In [ ]:
arr2

array([[2, 7, 9, 5],
       [3, 1, 1, 5],
       [8, 9, 5, 1]])

In [ ]:
~arr1 # negate (negative) operation

array([[ -8,  -3,  -7,  -5],
       [ -2,  -4,  -7,  -8],
       [ -4,  -4,  -2, -10]])

In [ ]:
arr1|arr2 # or operation

array([[ 7,  7, 15,  5],
       [ 3,  3,  7,  7],
       [11, 11,  5,  9]])

In [ ]:
arr1>arr2

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [False, False, False,  True]])

In [ ]:
#Numpy - String Functions.

In [ ]:
arr = np.array(['Ashraf' , "Sayyad"])

In [ ]:
arr

array(['Ashraf', 'Sayyad'], dtype='<U6')

In [ ]:
np.char.upper(arr)

array(['ASHRAF', 'SAYYAD'], dtype='<U6')

In [ ]:
np.char.title(arr)

array(['Ashraf', 'Sayyad'], dtype='<U6')

In [ ]:
np.char.capitalize(arr)

array(['Ashraf', 'Sayyad'], dtype='<U6')

In [ ]:
#Numpy - Mathematical Functions.

In [ ]:
arr1

array([[7, 2, 6, 4],
       [1, 3, 6, 7],
       [3, 3, 1, 9]])

In [ ]:
np.sin(arr1)

array([[ 0.6569866 ,  0.90929743, -0.2794155 , -0.7568025 ],
       [ 0.84147098,  0.14112001, -0.2794155 ,  0.6569866 ],
       [ 0.14112001,  0.14112001,  0.84147098,  0.41211849]])

In [ ]:
np.cos(arr1)

array([[ 0.75390225, -0.41614684,  0.96017029, -0.65364362],
       [ 0.54030231, -0.9899925 ,  0.96017029,  0.75390225],
       [-0.9899925 , -0.9899925 ,  0.54030231, -0.91113026]])

In [ ]:
np.tan(arr1)

array([[ 0.87144798, -2.18503986, -0.29100619,  1.15782128],
       [ 1.55740772, -0.14254654, -0.29100619,  0.87144798],
       [-0.14254654, -0.14254654,  1.55740772, -0.45231566]])

In [ ]:
np.tanh(arr1)

array([[0.99999834, 0.96402758, 0.99998771, 0.9993293 ],
       [0.76159416, 0.99505475, 0.99998771, 0.99999834],
       [0.99505475, 0.99505475, 0.76159416, 0.99999997]])

In [ ]:
np.log10(arr1)

array([[0.84509804, 0.30103   , 0.77815125, 0.60205999],
       [0.        , 0.47712125, 0.77815125, 0.84509804],
       [0.47712125, 0.47712125, 0.        , 0.95424251]])

In [ ]:
np.exp(arr1)

array([[1.09663316e+03, 7.38905610e+00, 4.03428793e+02, 5.45981500e+01],
       [2.71828183e+00, 2.00855369e+01, 4.03428793e+02, 1.09663316e+03],
       [2.00855369e+01, 2.00855369e+01, 2.71828183e+00, 8.10308393e+03]])

In [ ]:
np.sqrt(arr1)

array([[2.64575131, 1.41421356, 2.44948974, 2.        ],
       [1.        , 1.73205081, 2.44948974, 2.64575131],
       [1.73205081, 1.73205081, 1.        , 3.        ]])

In [ ]:
np.power(arr1,2)

array([[49,  4, 36, 16],
       [ 1,  9, 36, 49],
       [ 9,  9,  1, 81]])

In [ ]:
np.mean(arr1)

4.333333333333333

In [ ]:
np.median(arr1)

3.5

In [ ]:
np.std(arr1)

2.494438257849294

In [ ]:
np.var(arr1)

6.222222222222222

In [ ]:
np.min(arr1
      )

1

In [ ]:
np.max(arr1)

9