# Numpy_Part_1

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4]

In [ ]:
ar = np.array(l)

In [ ]:
ar

array([1, 2, 3, 4])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
a= [2,3,4]

In [ ]:
np.asanyarray(a)

array([2, 3, 4])

In [ ]:
b = np.matrix(l)

In [ ]:
b

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [ ]:
a = np.array(l)

In [ ]:
a


array([1, 2, 3, 4])

In [ ]:
c = a

In [ ]:
c

array([1, 2, 3, 4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
c[0] = 100

In [ ]:
c

array([100,   2,   3,   4])

In [ ]:
a

array([100,   2,   3,   4])

In [ ]:
d = np.copy(a)

In [ ]:
d

array([100,   2,   3,   4])

In [ ]:
a

array([100,   2,   3,   4])

In [ ]:
a[1] = 400

In [ ]:
a

array([100, 400,   3,   4])

In [ ]:
d

array([100,   2,   3,   4])

In [ ]:
c

array([100, 400,   3,   4])

In [ ]:
np.fromfunction(lambda i, j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [ ]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

In [ ]:
#Numpy - Data Types.

In [ ]:
l = [2,3,4,5,6]

In [ ]:
ar = np.array(l)

In [ ]:
ar

array([2, 3, 4, 5, 6])

In [ ]:
ar.ndim

1

In [ ]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [ ]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
ar2.ndim

2

In [ ]:
ar.size

5

In [ ]:
ar2.size

8

In [ ]:
ar

array([2, 3, 4, 5, 6])

In [ ]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
ar.shape

(5,)

In [ ]:
ar2.shape

(2, 4)

In [ ]:
ar.dtype

dtype('int64')

In [ ]:
ar2.dtype


dtype('int64')

In [ ]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])

In [ ]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [ ]:
ar22.dtype

dtype('float64')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [ ]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [ ]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
ar4 = np.zeros((3,4,2,3))

In [ ]:
ar4.ndim


4

In [ ]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
on =np.ones((2,3,2))

In [ ]:
on + 5


array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [ ]:
on *4


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [ ]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [ ]:
np.logspace(2,5 , 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [ ]:
np.logspace(2,5 , 10, base = 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [ ]:
np.logspace(2,5 , 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [ ]:
arr = np.random.randn(3,4)

In [ ]:
np.random.randn(3,4)

array([[ 0.77908754,  0.82238336,  1.52438804, -1.46169166],
       [ 1.02059057, -0.69594198,  0.41555804,  1.31067015],
       [-0.36008062,  0.19660196, -0.48989929, -0.84513704]])

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr)

0         1         2         3
0  1.530654  0.008142  0.123079  0.511778
1 -1.103861  0.293555  0.437360  1.413018
2 -0.316120  0.809642 -1.084107  1.054025

In [ ]:
np.random.rand(3,4)

array([[0.16411458, 0.68555398, 0.46356504, 0.85742871],
       [0.23925007, 0.9443199 , 0.31586792, 0.03907567],
       [0.76990168, 0.62083472, 0.47856843, 0.38456995]])

In [ ]:
np.random.randint(1,110,(3,4))

array([[ 30,  22,  56,  73],
       [ 75,  97, 107,  53],
       [ 15,  11,  13,  33]])

In [ ]:
np.random.randint(1,4,(3,4))

array([[2, 2, 3, 3],
       [3, 1, 1, 1],
       [3, 2, 2, 3]])

In [ ]:
np.random.randint(1,2,(3,4)) # range is 1 to 2 here 2 is excluded

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.random.randint(1,110 , (300,400))

array([[106,  18,  85, ...,  53,  95,  97],
       [ 56, 104,  28, ...,  57,  32,  15],
       [ 39,  82,  75, ...,   6,  85,  91],
       ...,
       [ 79,  42,  66, ...,  28,  56,  48],
       [109,  97, 105, ...,  28,  48,  93],
       [ 48,  58,  57, ...,  75,  55,  53]])

In [ ]:
pd.DataFrame(np.random.randint(1,110 , (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     77   88  101   71   25  106   97   56   89   97  ...   64   45   66   
1    108   61   99   93   49   13   75   32   13   15  ...   25   10    7   
2     88   89   94   33   78   43   28   84   78   78  ...   69   21   73   
3     40   74   14   26   46   72   25  100    5  107  ...   37   99   48   
4     64  106   38   79   28   22   63   11   35   68  ...   86   62   26   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   20   85   98   91   36   47   63   67   10   47  ...   90   67   59   
296   58   27   35   32   41   95   77   58   48    6  ...   56    6   75   
297   90   26   46  107   51   35   30   79   34   34  ...   15   85  103   
298   31   97  100   29   74   73   46   32   84    5  ...    7   19   55   
299   73   87   20   82  101   68   78   99   27    5  ...   81   90   56   

     393  394  395  396  397  398  399  
0     48   79   96   43    2   13   62  
1     14   62   92    7   70   97   82  
2     32   91  108   30  107   21   61  
3     36   87   49   42   13   85   37  
4    102   16   13  106    6   92   70  
..   ...  ...  ...  ...  ...  ...  ...  
295   42   68   44   58   51   82   32  
296   88   19   71   94   81   75   90  
297   49  105   89   85   37   37   35  
298  104   29  105   98   64   56   22  
299   84   39   28   22  103   11  108  

[300 rows x 400 columns]

In [ ]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('test.csv')

In [ ]:
arr = np.random.rand(3,4)

In [ ]:
arr

array([[0.97622515, 0.97421073, 0.75799879, 0.54535098],
       [0.31805373, 0.21872034, 0.52571352, 0.61684153],
       [0.05124143, 0.04267771, 0.83983415, 0.59824673]])

In [ ]:
arr.reshape(6,2)

array([[0.97622515, 0.97421073],
       [0.75799879, 0.54535098],
       [0.31805373, 0.21872034],
       [0.52571352, 0.61684153],
       [0.05124143, 0.04267771],
       [0.83983415, 0.59824673]])

In [ ]:
arr.reshape(6,-1)

array([[0.97622515, 0.97421073],
       [0.75799879, 0.54535098],
       [0.31805373, 0.21872034],
       [0.52571352, 0.61684153],
       [0.05124143, 0.04267771],
       [0.83983415, 0.59824673]])

In [ ]:
arr.reshape(6,-2)

array([[0.97622515, 0.97421073],
       [0.75799879, 0.54535098],
       [0.31805373, 0.21872034],
       [0.52571352, 0.61684153],
       [0.05124143, 0.04267771],
       [0.83983415, 0.59824673]])

In [ ]:
arr.reshape(6,-34567)

array([[0.97622515, 0.97421073],
       [0.75799879, 0.54535098],
       [0.31805373, 0.21872034],
       [0.52571352, 0.61684153],
       [0.05124143, 0.04267771],
       [0.83983415, 0.59824673]])

In [ ]:
arr1 = arr.reshape(6,-134353553435)

In [ ]:
arr1

array([[0.97622515, 0.97421073],
       [0.75799879, 0.54535098],
       [0.31805373, 0.21872034],
       [0.52571352, 0.61684153],
       [0.05124143, 0.04267771],
       [0.83983415, 0.59824673]])

In [ ]:
arr1[1][1]

0.5453509822066328

In [ ]:
arr1[2:5]

array([[0.31805373, 0.21872034],
       [0.52571352, 0.61684153],
       [0.05124143, 0.04267771]])

In [ ]:
arr1[2:5,1]

array([0.21872034, 0.61684153, 0.04267771])

In [ ]:
arr = np.random.randint(1,100 , (5,5))

In [ ]:
arr

array([[25, 96, 57, 27, 40],
       [26, 38, 29, 95,  4],
       [84, 66, 21, 27,  7],
       [34, 72, 78, 36,  9],
       [ 7, 72, 71,  1, 32]])

In [ ]:
arr[arr>50]

array([96, 57, 95, 84, 66, 72, 78, 72, 71])

In [ ]:
arr>50


array([[False,  True,  True, False, False],
       [False, False, False,  True, False],
       [ True,  True, False, False, False],
       [False,  True,  True, False, False],
       [False,  True,  True, False, False]])

In [ ]:
arr

array([[25, 96, 57, 27, 40],
       [26, 38, 29, 95,  4],
       [84, 66, 21, 27,  7],
       [34, 72, 78, 36,  9],
       [ 7, 72, 71,  1, 32]])

In [ ]:
arr[2:4 , [1,2]]

array([[66, 21],
       [72, 78]])

In [ ]:
arr[0][0] = 5000

In [ ]:
arr

array([[5000,   96,   57,   27,   40],
       [  26,   38,   29,   95,    4],
       [  84,   66,   21,   27,    7],
       [  34,   72,   78,   36,    9],
       [   7,   72,   71,    1,   32]])

In [ ]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [ ]:
arr1

array([[2, 2, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [ ]:
arr2


array([[2, 1, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [ ]:
arr1+arr2

array([[4, 3, 2],
       [2, 4, 3],
       [3, 3, 2]])

In [ ]:
arr1-arr2

array([[ 0,  1,  0],
       [ 0,  0,  1],
       [ 1, -1,  0]])

In [ ]:
arr1/arr2

array([[1. , 2. , 1. ],
       [1. , 1. , 2. ],
       [2. , 0.5, 1. ]])

In [ ]:
arr1 * arr2 # simple indexwise multiplication

array([[4, 2, 1],
       [1, 4, 2],
       [2, 2, 1]])

In [ ]:
arr1

array([[2, 2, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [ ]:
arr2

array([[2, 1, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [ ]:
arr1@arr2 #matrix multiplication

array([[7, 8, 5],
       [6, 9, 5],
       [6, 6, 4]])

In [ ]:
arr1/0

<ipython-input-117-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
arr1 +100

array([[102, 102, 101],
       [101, 102, 102],
       [102, 101, 101]])

In [ ]:
arr1**2

array([[4, 4, 1],
       [1, 4, 4],
       [4, 1, 1]])

In [ ]:
#Numpy – Broadcasting.

In [ ]:
arr =np.zeros((4,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
row = np.array([1,2,3,4])

In [ ]:
row.shape

(4,)

In [ ]:
arr + row # row Broadcasting # rowwise addition

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
row.T

array([1, 2, 3, 4])

In [ ]:
col = np.array([[1,2,3,4]])

In [ ]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [ ]:
col

array([[1, 2, 3, 4]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr1 = np.random.randint(1,4 , (3,4))

In [ ]:
arr1

array([[3, 2, 1, 2],
       [2, 2, 3, 2],
       [3, 3, 3, 3]])

In [ ]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.73205081, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081]])

In [ ]:
np.exp(arr1)

array([[20.08553692,  7.3890561 ,  2.71828183,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 , 20.08553692,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692, 20.08553692]])

In [ ]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.30103   , 0.47712125, 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125]])