# Numpy_Part_3

In [1]:
#Sort, Search & Counting Functions.

In [2]:
import numpy as np

In [3]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [4]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [5]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [6]:
np.searchsorted(arr ,34)

12

In [7]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [8]:
np.count_nonzero(arr1)

2

In [9]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [10]:
np.where(arr > 6)

(array([5, 8]),)

In [11]:
np.extract(arr>3 , arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [12]:
#Numpy - Byte Swapping.

In [13]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [14]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [15]:
#Numpy - Copies &Views.

In [16]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [17]:
a = np.copy(arr) # deep copy, when you are changing in arr not affect in a

In [18]:
b = arr.view() # salow copy, when you are changing in arr also change in b

In [19]:
b = arr

In [20]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [21]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
b[0] = 67

In [23]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [24]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [25]:
#Numpy - Matrix Library.

In [26]:
import numpy.matlib as nm

In [27]:
nm.zeros(5 #Matrix Library.
        )

matrix([[0., 0., 0., 0., 0.]])

In [28]:
nm.ones((3,4)) # Matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
nm.eye(5) # identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [44]:
#Numpy - Linear Algebra

In [45]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [46]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [47]:
arr1

array([[0, 1],
       [2, 0]])

In [48]:
arr2

array([[1, 0],
       [0, 2]])

In [49]:
np.dot(arr1, arr2)

array([[0, 2],
       [2, 0]])

In [50]:
arr1@arr2 # matrix multiplication in array

array([[0, 2],
       [2, 0]])